name: CI Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read
  packages: write

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      REPO_LC: ${{ github.repository }} # will be lowercased in shell

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Test (install, train, unit tests)
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt pytest
          python src/train-v0.2.py
          PYTHONPATH=$(pwd) pytest -q

      - name: Build Docker image (tag v0.2)
        run: |
          REPO_LC=$(echo "${REPO_LC}" | tr '[:upper:]' '[:lower:]')
          IMAGE="ghcr.io/${REPO_LC}"
          docker build -t "${IMAGE}:v0.2" .

      - name: Smoke test
        shell: bash
        run: |
          set -euo pipefail
          REPO_LC=$(echo "${REPO_LC}" | tr '[:upper:]' '[:lower:]')
          IMAGE="ghcr.io/${REPO_LC}:v0.2"
          CID=ci-smoke
          docker run -d --name "$CID" -p 8000:8000 "$IMAGE"
          trap 'docker logs "$CID" || true; docker rm -f "$CID" || true' EXIT
          for i in {1..30}; do
            if curl -fsS http://localhost:8000/health >/dev/null; then
              echo "Healthcheck OK"
              exit 0
            fi
            sleep 1
          done
          echo "Healthcheck failed"
          exit 1

      - name: Log in to GHCR
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image (v0.2)
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          REPO_LC=$(echo "${REPO_LC}" | tr '[:upper:]' '[:lower:]')
          IMAGE="ghcr.io/${REPO_LC}:v0.2"
          docker push "$IMAGE"
