name: CI Pipeline

# Trigger on push or PR
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Setup Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    # Step 4: Run tests
    - name: Run tests
      run: pytest

    # Step 5: Build Docker image
    - name: Build Docker image
      run: docker build -t diabetes-api .

    # Step 6: Smoke test container
    - name: Run container smoke test
      run: |
        docker run -d -p 8000:8000 diabetes-api
        # Wait for server to be up before testing health endpoint
        sleep 5
        curl -f http://localhost:8000/health
        docker ps -q | xargs docker stop
