name: Release

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v0.1, v0.2

permissions:
  contents: read
  packages: write

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model dynamically based on tag
        run: |
          # Extract version (e.g. v0.1 → 0.1)
          VERSION="${GITHUB_REF#refs/tags/v}"
          echo "Using VERSION=$VERSION"

          # Match to training script name
          TRAIN_SCRIPT="src/train-v$VERSION.py"
          echo "Looking for training script: $TRAIN_SCRIPT"

          # Check existence
          if [ ! -f "$TRAIN_SCRIPT" ]; then
            echo "❌ Script $TRAIN_SCRIPT not found."
            exit 1
          fi

          # Run training script with --version
          python "$TRAIN_SCRIPT" --version "$VERSION"

      - uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: artifacts/*

  build-and-push:
    needs: train
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: artifacts

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image name and tag
        id: vars
        run: |
          IMAGE_NAME=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          TAG=${GITHUB_REF##*/}
          echo "image=$IMAGE_NAME" >> $GITHUB_OUTPUT
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.tag }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.tag }}
